stages:
  - publish
  - deploy
  - deploy2

#before_script:
#    - source gitbuildvariables.env

variables:
  APP_NAME: zohomail
  DEPLOY_SERVER_IP: APPS_SERVER_PROD
  SERVER_USER: azureuser
  ID_RSA: ID_RSA_GENERIC_SERVER
  DOCKER_TAG: latest #$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_NAME: pronnelapp-$APP_NAME-$CI_COMMIT_REF_NAME:$DOCKER_TAG
  DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE/pronnelapp-$APP_NAME-$CI_COMMIT_REF_NAME:$DOCKER_TAG
  ENVIRONMENT: $CI_COMMIT_REF_NAME
  REPOSITORY_NAME_LOG: pronnelapp-$APP_NAME-$CI_COMMIT_REF_NAME
  REPOSITORY_NAME_API1: pronnelapp-$APP_NAME-1$CI_COMMIT_REF_NAME
  REPOSITORY_NAME_API2: pronnelapp-$APP_NAME-2$CI_COMMIT_REF_NAME

publishstaging:
  stage: publish
  tags:
    - publish
  script:
    - echo $ENVIRONMENT $REPOSITORY_NAME_API1
    - echo $DOCKER_IMAGE_NAME $DOCKER_IMAGE_TAG
    - docker build -t $DOCKER_IMAGE_NAME --network=host  .
    - docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_TAG
    - docker push $DOCKER_IMAGE_TAG

  rules:
    - if: $CI_COMMIT_REF_NAME == "dev2environment"
    - if: $CI_COMMIT_REF_NAME == "dev1environment"
    - if: $CI_COMMIT_REF_NAME == "releasev1prod1"


deploy:
  stage: deploy
  tags:
    - deployment
  script:
    - |
      if [[ "$CI_COMMIT_REF_NAME" == "dev1environment" ]]; then
        export NODE_ENV="dev1"
        eval "SERVER_IP=\$APPS_SERVER_DEV1"
      elif [[ "$CI_COMMIT_REF_NAME" == *"release"* ]]; then
        export NODE_ENV="prod"
        eval "SERVER_IP=\$APPS_SERVER_PROD"
      elif [[ "$CI_COMMIT_REF_NAME" == "dev2environment" ]]; then
        export NODE_ENV="dev2"
        eval "SERVER_IP=\$APPS_SERVER_DEV2"
      else
        export NODE_ENV="dev1"
        eval "SERVER_IP=\$APPS_SERVER_DEV1"
      fi
      echo "NODE_ENV is $NODE_ENV"
      echo "SERVER_IP is $SERVER_IP"
    - eval "SERVER_IP=\$$DEPLOY_SERVER_IP"
    - echo $SERVER_IP
    - chmod og= ${!ID_RSA}
    - ssh -i ${!ID_RSA} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $DOCKER_IMAGE_TAG"
    - ssh -i ${!ID_RSA} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f $REPOSITORY_NAME_API1 || true"
    - ssh -i ${!ID_RSA} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run --log-driver=journald   --log-opt tag=$REPOSITORY_NAME_LOG -e SERVER_NUMBER=0 -e PRONNEL_ENV_VALUE=$ENVIRONMENT --net=host -d --name $REPOSITORY_NAME_API1 $DOCKER_IMAGE_TAG"

  environment:
    name: production
    url: http://your_server_IP
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev2environment"
    - if: $CI_COMMIT_REF_NAME == "dev1environment"
    - if: $CI_COMMIT_REF_NAME == "releasev1prod1"


#deploy2:
#  stage: deploy2
#  tags:
#    - deployment
#  script:
#    - chmod og= ${!ID_RSA}
#    - ssh -i ${!ID_RSA} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $DOCKER_IMAGE_TAG"
#    - ssh -i ${!ID_RSA} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f $REPOSITORY_NAME_API2 || true"
#    - ssh -i ${!ID_RSA} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run --log-driver=journald   --log-opt tag=$REPOSITORY_NAME_LOG -e SERVER_NUMBER=1  -e PRONNEL_ENV_VALUE=$ENVIRONMENT --net=host -d --name $REPOSITORY_NAME_API2 $DOCKER_IMAGE_TAG"
#  rules:
#    - if: $CI_COMMIT_REF_NAME == "devenvironment"
#      when: delayed
#      start_in: 1 minutes
